### ISSUE TITLE
KEGG pathway download ERROR

### ISSUE THREAD

**Issue by yellowcun** [gitools/gitools#160]
org.gitools.datasources.idmapper.MappingException: java.io.IOException: Server returned HTTP response code: 400 for URL: http://rest.kegg.jp/link/genes/path:eco00730
org.gitools.datasources.modules.importer.ModulesImporterException: org.gitools.datasources.idmapper.MappingException: java.io.IOException: Server returned HTTP response code: 400 for URL: http://rest.kegg.jp/link/genes/path:eco00730
	at org.gitools.datasources.kegg.modules.EnsemblKeggModulesImporter.importMap(EnsemblKeggModulesImporter.java:580)
	at org.gitools.ui.app.actions.file.AbstractImportModulesAction$1.run(AbstractImportModulesAction.java:79)
	at org.gitools.ui.platform.progress.JobThread$5.run(JobThread.java:177)
	at org.gitools.ui.platform.progress.JobThread$4.run(JobThread.java:153)
Caused by: org.gitools.datasources.idmapper.MappingException: java.io.IOException: Server returned HTTP response code: 400 for URL: http://rest.kegg.jp/link/genes/path:eco00730
	at org.gitools.datasources.kegg.idmapper.KeggPathwaysMapper.map(KeggPathwaysMapper.java:81)
	at org.gitools.datasources.idmapper.MappingEngine.run(MappingEngine.java:225)
	at org.gitools.datasources.kegg.modules.EnsemblKeggModulesImporter.importMap(EnsemblKeggModulesImporter.java:558)
	... 3 more
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://rest.kegg.jp/link/genes/path:eco00730
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at org.gitools.datasources.kegg.service.KeggService.createReader(KeggService.java:148)
	at org.gitools.datasources.kegg.service.KeggService.getGenesByPathway(KeggService.java:120)
	at org.gitools.datasources.kegg.idmapper.KeggPathwaysMapper.map(KeggPathwaysMapper.java:76)
	... 5 more

**Comment by jordeu** [comment]
Thanks for the report. How can I reproduce this error?

**Comment by yellowcun** [comment]
"Download - Modules - KEGG pathway"

I was trying to download the pathway information of E.coli MG1655 from KEGG.
